name: CI - DVC Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dvc-ci:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USER }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install "dvc[s3]"



      - name: DVC Pull
        run: |
          dvc pull -r dagshub_remote -v

      - name: Run DVC pipeline
        run: |
          dvc repro -v

      - name: Show metrics
        run: |
          echo "Baseline metrics:"
          cat metrics.json || true
          echo "RandomForest metrics:"
          cat metrics_rf.json || true
